#cloud-config
users:
  - name: ${username}
    lock_passwd: false
    passwd: ${password}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
ssh_pwauth: true
disable_root: false

write_files:
- path: /etc/netplan/50-cloud-init.yaml
  content: |
    network:
      version: 2
      ethernets:
        ens160:
          dhcp4: false
          addresses: [${ipaddress}/16]
          nameservers:
            addresses: 
            - ${nameserver1}
            - ${nameserver2}
          routes:
            - to: default
              via: ${defaultgateway}

- path: /etc/apt/apt.conf.d/90_no_prompt
  content: | 
    APT::Get::Assume-Yes "true";
    APT::Get::force-yes "true";

- path: /etc/sysctl.d/10-disable-ipv6.conf
  permissions: 0644
  owner: root
  content: |
    net.ipv6.conf.eth0.disable_ipv6 = 1

runcmd:
- [netplan, apply]
- [apt, update]
- [apt, upgrade, -y]
- [apt, install, dnsutils, traceroute, net-tools, -y]