#!/usr/bin/env groovy

pipeline{
    agent any

    parameters {
        choice(name: 'CHOICE_PARAM', choices: ['ONE','TWO'], description: '')
        string(name: 'STRING_PARAM', defaultValue: 'ME', description: 'desc')
        booleanParam(defaultValue: true, name: 'Bool')
    }
    
    stages{
       
        stage("Prepare for deploy") {
            sh "echo hello!"
        }
        stage("Deploy Clusters") {
            // build_clusters(params.total_num_of_clusters)
            sh "echo deploy"
        }
    }
}

// @NonCPS 
// def build_clusters(total_num_of_clusters) {
//     for (cluster=0; cluster < total_num_of_clusters.size(); cluster++) {
//         sh `export CLUSTER_NUM=${cluster}`
//         sh `docker-compose -f ./docker/docker-compose.yaml up -d &
//     }
// }