Mu- name: Install packages
  become: true
  shell: "{{ item }}"
  with_items:
  - apt -y install curl apt-transport-https
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt update
  - apt -y install vim git curl wget kubelet kubeadm kubectl
  - "apt-mark hold kubelet={{ ansible_env.KUBE_VER }} kubeadm={{ ansible_env.KUBE_VER }} kubectl={{ ansible_env.KUBE_VER }}"
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  - swapoff -a
  - modprobe overlay
  - modprobe br_netfilter

- name: Update IPtables for Kubernetes
  become: true 
  shell: 
    cmd: |
      tee /etc/sysctl.d/kubernetes.conf<<EOF
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      EOF


- name: Install Docker and Mirantis
  shell: "{{ item }}"
  become: true
  with_items: 
  - apt update
  - apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt install -y docker-ce docker-ce-cli
